Repository Teg3z/Wheel-of-Luck, pull requests merged in 2024-09, with the labels that each got.

#26 Replace blocking sleep call for non-blocking
  wheel_of_luck.py
Labels: bug

#28 Remove categories
  db_handler.py
  wheel_of_luck.py
Labels: enhancement

#33 Fix/last spin insertion
  db_handler.py
  wheel_of_luck.py
Labels: bug

#34 Bugfix/fix build automation
  .github/workflows/build_packages.yml
  setup.py
Labels: bug, DevOps

#38 Docs/last spin logic change
  db_handler.py
  wheel_of_luck.py
Labels: documentation

#40 Implement games addition by user via DC
  db_handler.py
  discord_bot.py
Labels: enhancement

#42 Bugfix/improve cx freeze implementation
  .github/workflows/build_packages.yml
  setup.py
Labels: DevOps

#44 Reorganize projects structure
  assets/genieli_design.png
  setup.py
  src/db_handler.py
  src/discord_bot.py
  src/env_var_loader.py
  src/game.py
  src/multi_entry_col_parser.py
  src/player.py
  src/wheel_of_luck.py
Labels: enhancement

#46 Bugfix/mygames command
  src/db_handler.py
  src/discord_bot.py
Labels: bug

#47 Increment action versions, modernize env handovers
  .github/workflows/pylint.yml
Labels: bug

#51 Devops/basic testing
  .github/workflows/test.yml
  src/db_handler.py
  src/player.py
  tests/test_db.py
  tests/test_game.py
  tests/test_player.py
Labels: enhancement, DevOps, QA
