Repository Teg3z/Wheel-of-Luck, pull requests merged in 2024-08, with the labels that each got.

#9 Add TEST button
  discord_bot.py
  wheel_of_luck.py
Labels: enhancement

#18 Feature/auto linter
  .github/workflows/pylint.yml
Labels: DevOps

#23 Add a feedback element to the linter outputs
  .github/workflows/pylint.yml
Labels: enhancement, DevOps, QA

#24 Prepare release artifact WF
  .github/workflows/build_packages.yml
  installer.py
  requirements.txt
  setup.py
Labels: DevOps

#25 Bugfix/suppress import errors
  .github/workflows/pylint.yml
Labels: enhancement, DevOps
